#ifndef _PRECISION_TEST_FPDATA_H_
#define _PRECISION_TEST_FPDATA_H_

// Script version 1.3

// SMALL_NUM_INSTANCE  1
// MEDIUM_NUM_INSTANCE 1
// FAST_NUM_INSTANCE   1

//
// LAYER 1
//

// LAYER1-SMALL-Team:      this
// LAYER1-SMALL-uArch:     this
// LAYER1-SMALL-Inst:      this
// LAYER1-SMALL-Area:      this
// LAYER1-SMALL-EffLat:    this
// LAYER1-SMALL-GitRev:    this

// LAYER1-MEDIUM-Team:     this
// LAYER1-MEDIUM-uArch:    this
// LAYER1-MEDIUM-Inst:     this
// LAYER1-MEDIUM-Area:     this
// LAYER1-MEDIUM-EffLat:   this
// LAYER1-MEDIUM-GitRev:   this

// LAYER1-FAST-Team:       this
// LAYER1-FAST-uArch:      this
// LAYER1-FAST-Inst:       this
// LAYER1-FAST-Area:       this
// LAYER1-FAST-EffLat:     this
// LAYER1-FAST-GitRev:     this

//
// Layer 1
//

#define SMALL_LAYER_FPDATA_WL_1     this
#define SMALL_LAYER_W_FPDATA_WL_1   this
#define SMALL_LAYER_FPDATA_IL_1     this
#define SMALL_LAYER_W_FPDATA_IL_1   this

#define MEDIUM_LAYER_FPDATA_WL_1    this
#define MEDIUM_LAYER_W_FPDATA_WL_1  this
#define MEDIUM_LAYER_FPDATA_IL_1    this
#define MEDIUM_LAYER_W_FPDATA_IL_1  this

#define FAST_LAYER_FPDATA_WL_1      this
#define FAST_LAYER_W_FPDATA_WL_1    this
#define FAST_LAYER_FPDATA_IL_1      this
#define FAST_LAYER_W_FPDATA_IL_1    this

#ifdef TARGET_LAYER_1
// This is the target layer
#define LAYER_FPDATA_WL_1     FPDATA_WL
#define LAYER_W_FPDATA_WL_1   W_FPDATA_WL
#define LAYER_FPDATA_IL_1     FPDATA_IL
#define LAYER_W_FPDATA_IL_1   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_1     SMALL_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   SMALL_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     SMALL_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   SMALL_LAYER_W_FPDATA_IL_1
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_1     MEDIUM_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   MEDIUM_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     MEDIUM_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   MEDIUM_LAYER_W_FPDATA_IL_1
#else
#define LAYER_FPDATA_WL_1     FAST_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   FAST_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     FAST_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   FAST_LAYER_W_FPDATA_IL_1
#endif
#endif // TARGET_LAYER_1

//
// LAYER 2
//

// LAYER2-SMALL-Team:      2b
// LAYER2-SMALL-uArch:     SMALL
// LAYER2-SMALL-Inst:      1
// LAYER2-SMALL-Area:      3.49504613333333
// LAYER2-SMALL-EffLat:    0.78668
// LAYER2-SMALL-GitRev:    7844f9042cbfbda9b37cfd7271b9254fe8f0247a

// LAYER2-MEDIUM-Team:     2b
// LAYER2-MEDIUM-uArch:    FAST
// LAYER2-MEDIUM-Inst:     1
// LAYER2-MEDIUM-Area:     4.08536266666667
// LAYER2-MEDIUM-EffLat:   0.4093551
// LAYER2-MEDIUM-GitRev:   742f795f5a5e536a4f38f457db4d628bd84e0b71

// LAYER2-FAST-Team:       2l
// LAYER2-FAST-uArch:      SMALL
// LAYER2-FAST-Inst:       1
// LAYER2-FAST-Area:       8.664176
// LAYER2-FAST-EffLat:     0.314505
// LAYER2-FAST-GitRev:     eb5b934b016aaa8b0824ea0382f734d461626618

//
// Layer 2
//

#define SMALL_LAYER_FPDATA_WL_2     17
#define SMALL_LAYER_W_FPDATA_WL_2   14
#define SMALL_LAYER_FPDATA_IL_2     7
#define SMALL_LAYER_W_FPDATA_IL_2   7

#define MEDIUM_LAYER_FPDATA_WL_2    NA
#define MEDIUM_LAYER_W_FPDATA_WL_2  NA
#define MEDIUM_LAYER_FPDATA_IL_2    NA
#define MEDIUM_LAYER_W_FPDATA_IL_2  NA

#define FAST_LAYER_FPDATA_WL_2      32
#define FAST_LAYER_W_FPDATA_WL_2    32
#define FAST_LAYER_FPDATA_IL_2      17
#define FAST_LAYER_W_FPDATA_IL_2    16

#ifdef TARGET_LAYER_2
// This is the target layer
#define LAYER_FPDATA_WL_2     FPDATA_WL
#define LAYER_W_FPDATA_WL_2   W_FPDATA_WL
#define LAYER_FPDATA_IL_2     FPDATA_IL
#define LAYER_W_FPDATA_IL_2   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_2     SMALL_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   SMALL_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     SMALL_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   SMALL_LAYER_W_FPDATA_IL_2
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_2     MEDIUM_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   MEDIUM_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     MEDIUM_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   MEDIUM_LAYER_W_FPDATA_IL_2
#else
#define LAYER_FPDATA_WL_2     FAST_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   FAST_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     FAST_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   FAST_LAYER_W_FPDATA_IL_2
#endif
#endif // TARGET_LAYER_2

//
// LAYER 3
//

// LAYER3-SMALL-Team:      3i
// LAYER3-SMALL-uArch:     SMALL
// LAYER3-SMALL-Inst:      1
// LAYER3-SMALL-Area:      3.25986026666667
// LAYER3-SMALL-EffLat:    12.555598
// LAYER3-SMALL-GitRev:    88adf68c27376d80be3ccfacafc33f6968fca64a

// LAYER3-MEDIUM-Team:     3a
// LAYER3-MEDIUM-uArch:    MEDIUM
// LAYER3-MEDIUM-Inst:     1
// LAYER3-MEDIUM-Area:     3.73635266666667
// LAYER3-MEDIUM-EffLat:   2.33131183
// LAYER3-MEDIUM-GitRev:   8c8201e2ac154286f930d0528be4d7a51d43af8b

// LAYER3-FAST-Team:       3c
// LAYER3-FAST-uArch:      FAST
// LAYER3-FAST-Inst:       1
// LAYER3-FAST-Area:       7.30700506666667
// LAYER3-FAST-EffLat:     1.2077052
// LAYER3-FAST-GitRev:     6df5fc18eb6cf69eb4fba846486efabe6f31e2a8

//
// Layer 3
//

#define SMALL_LAYER_FPDATA_WL_3     18
#define SMALL_LAYER_W_FPDATA_WL_3   18
#define SMALL_LAYER_FPDATA_IL_3     9
#define SMALL_LAYER_W_FPDATA_IL_3   8

#define MEDIUM_LAYER_FPDATA_WL_3    32
#define MEDIUM_LAYER_W_FPDATA_WL_3  32
#define MEDIUM_LAYER_FPDATA_IL_3    17
#define MEDIUM_LAYER_W_FPDATA_IL_3  16

#define FAST_LAYER_FPDATA_WL_3      18
#define FAST_LAYER_W_FPDATA_WL_3    18
#define FAST_LAYER_FPDATA_IL_3      9
#define FAST_LAYER_W_FPDATA_IL_3    8

#ifdef TARGET_LAYER_3
// This is the target layer
#define LAYER_FPDATA_WL_3     FPDATA_WL
#define LAYER_W_FPDATA_WL_3   W_FPDATA_WL
#define LAYER_FPDATA_IL_3     FPDATA_IL
#define LAYER_W_FPDATA_IL_3   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_3     SMALL_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   SMALL_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     SMALL_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   SMALL_LAYER_W_FPDATA_IL_3
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_3     MEDIUM_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   MEDIUM_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     MEDIUM_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   MEDIUM_LAYER_W_FPDATA_IL_3
#else
#define LAYER_FPDATA_WL_3     FAST_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   FAST_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     FAST_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   FAST_LAYER_W_FPDATA_IL_3
#endif
#endif // TARGET_LAYER_3

//
// LAYER 4
//

// LAYER4-SMALL-Team:      4d
// LAYER4-SMALL-uArch:     SMALL
// LAYER4-SMALL-Inst:      1
// LAYER4-SMALL-Area:      2.86778893333333
// LAYER4-SMALL-EffLat:    14.283064
// LAYER4-SMALL-GitRev:    e324b9c1310398368bf22d8e29ebd18649d3966f

// LAYER4-MEDIUM-Team:     4g
// LAYER4-MEDIUM-uArch:    SMALL
// LAYER4-MEDIUM-Inst:     1
// LAYER4-MEDIUM-Area:     2.89612866666667
// LAYER4-MEDIUM-EffLat:   1.4701661
// LAYER4-MEDIUM-GitRev:   2474802967de0c8d930c9126bbfcf185649e3a87

// LAYER4-FAST-Team:       4c
// LAYER4-FAST-uArch:      FAST
// LAYER4-FAST-Inst:       1
// LAYER4-FAST-Area:       13.273366
// LAYER4-FAST-EffLat:     0.9183361
// LAYER4-FAST-GitRev:     7aadd58060819e6138c75978344982647bfa44e6

//
// Layer 4
//

#define SMALL_LAYER_FPDATA_WL_4     17
#define SMALL_LAYER_W_FPDATA_WL_4   17
#define SMALL_LAYER_FPDATA_IL_4     9
#define SMALL_LAYER_W_FPDATA_IL_4   8

#define MEDIUM_LAYER_FPDATA_WL_4    32
#define MEDIUM_LAYER_W_FPDATA_WL_4  32
#define MEDIUM_LAYER_FPDATA_IL_4    17
#define MEDIUM_LAYER_W_FPDATA_IL_4  16

#define FAST_LAYER_FPDATA_WL_4      17
#define FAST_LAYER_W_FPDATA_WL_4    17
#define FAST_LAYER_FPDATA_IL_4      9
#define FAST_LAYER_W_FPDATA_IL_4    8

#ifdef TARGET_LAYER_4
// This is the target layer
#define LAYER_FPDATA_WL_4     FPDATA_WL
#define LAYER_W_FPDATA_WL_4   W_FPDATA_WL
#define LAYER_FPDATA_IL_4     FPDATA_IL
#define LAYER_W_FPDATA_IL_4   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_4     SMALL_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   SMALL_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     SMALL_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   SMALL_LAYER_W_FPDATA_IL_4
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_4     MEDIUM_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   MEDIUM_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     MEDIUM_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   MEDIUM_LAYER_W_FPDATA_IL_4
#else
#define LAYER_FPDATA_WL_4     FAST_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   FAST_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     FAST_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   FAST_LAYER_W_FPDATA_IL_4
#endif
#endif // TARGET_LAYER_4

//
// LAYER 5
//

// LAYER5-SMALL-Team:      5x
// LAYER5-SMALL-uArch:     SMALL
// LAYER5-SMALL-Inst:      1
// LAYER5-SMALL-Area:      0.5
// LAYER5-SMALL-EffLat:    0.8619
// LAYER5-SMALL-GitRev:    fd69a351a5aa21fdaceb6e7eb00131568

// LAYER5-MEDIUM-Team:     5y
// LAYER5-MEDIUM-uArch:    FAST
// LAYER5-MEDIUM-Inst:     1
// LAYER5-MEDIUM-Area:     0.9
// LAYER5-MEDIUM-EffLat:   0.4619
// LAYER5-MEDIUM-GitRev:   fd69a351a5aa21fdaceb6e7eb00131568

// LAYER5-FAST-Team:       5z
// LAYER5-FAST-uArch:      FAST
// LAYER5-FAST-Inst:       1
// LAYER5-FAST-Area:       2.2
// LAYER5-FAST-EffLat:     0.1619
// LAYER5-FAST-GitRev:     fd69a351a5aa21fdaceb6e7eb00131568

//
// Layer 5
//

#define SMALL_LAYER_FPDATA_WL_5     32
#define SMALL_LAYER_W_FPDATA_WL_5   32
#define SMALL_LAYER_FPDATA_IL_5     17
#define SMALL_LAYER_W_FPDATA_IL_5   16

#define MEDIUM_LAYER_FPDATA_WL_5    32
#define MEDIUM_LAYER_W_FPDATA_WL_5  32
#define MEDIUM_LAYER_FPDATA_IL_5    17
#define MEDIUM_LAYER_W_FPDATA_IL_5  16

#define FAST_LAYER_FPDATA_WL_5      32
#define FAST_LAYER_W_FPDATA_WL_5    32
#define FAST_LAYER_FPDATA_IL_5      17
#define FAST_LAYER_W_FPDATA_IL_5    16

#ifdef TARGET_LAYER_5
// This is the target layer
#define LAYER_FPDATA_WL_5     FPDATA_WL
#define LAYER_W_FPDATA_WL_5   W_FPDATA_WL
#define LAYER_FPDATA_IL_5     FPDATA_IL
#define LAYER_W_FPDATA_IL_5   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_5     SMALL_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   SMALL_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     SMALL_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   SMALL_LAYER_W_FPDATA_IL_5
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_5     MEDIUM_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   MEDIUM_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     MEDIUM_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   MEDIUM_LAYER_W_FPDATA_IL_5
#else
#define LAYER_FPDATA_WL_5     FAST_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   FAST_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     FAST_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   FAST_LAYER_W_FPDATA_IL_5
#endif
#endif // TARGET_LAYER_5

//
// LAYER 6
//

// LAYER6-SMALL-Team:      6x
// LAYER6-SMALL-uArch:     SMALL
// LAYER6-SMALL-Inst:      1
// LAYER6-SMALL-Area:      0.7
// LAYER6-SMALL-EffLat:    0.7619
// LAYER6-SMALL-GitRev:    fd69a351a5aa21fdaceb6e7eb00131568

// LAYER6-MEDIUM-Team:     6z
// LAYER6-MEDIUM-uArch:    SMALL
// LAYER6-MEDIUM-Inst:     1
// LAYER6-MEDIUM-Area:     5
// LAYER6-MEDIUM-EffLat:   0.0719
// LAYER6-MEDIUM-GitRev:   fd69a351a5aa21fdaceb6e7eb00131568

// LAYER6-FAST-Team:       6z
// LAYER6-FAST-uArch:      FAST
// LAYER6-FAST-Inst:       1
// LAYER6-FAST-Area:       15
// LAYER6-FAST-EffLat:     0.0119
// LAYER6-FAST-GitRev:     fd69a351a5aa21fdaceb6e7eb00131568

//
// Layer 6
//

#define SMALL_LAYER_FPDATA_WL_6     32
#define SMALL_LAYER_W_FPDATA_WL_6   32
#define SMALL_LAYER_FPDATA_IL_6     17
#define SMALL_LAYER_W_FPDATA_IL_6   16

#define MEDIUM_LAYER_FPDATA_WL_6    32
#define MEDIUM_LAYER_W_FPDATA_WL_6  32
#define MEDIUM_LAYER_FPDATA_IL_6    17
#define MEDIUM_LAYER_W_FPDATA_IL_6  16

#define FAST_LAYER_FPDATA_WL_6      32
#define FAST_LAYER_W_FPDATA_WL_6    32
#define FAST_LAYER_FPDATA_IL_6      17
#define FAST_LAYER_W_FPDATA_IL_6    16

#ifdef TARGET_LAYER_6
// This is the target layer
#define LAYER_FPDATA_WL_6     FPDATA_WL
#define LAYER_W_FPDATA_WL_6   W_FPDATA_WL
#define LAYER_FPDATA_IL_6     FPDATA_IL
#define LAYER_W_FPDATA_IL_6   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_6     SMALL_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   SMALL_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     SMALL_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   SMALL_LAYER_W_FPDATA_IL_6
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_6     MEDIUM_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   MEDIUM_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     MEDIUM_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   MEDIUM_LAYER_W_FPDATA_IL_6
#else
#define LAYER_FPDATA_WL_6     FAST_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   FAST_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     FAST_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   FAST_LAYER_W_FPDATA_IL_6
#endif
#endif // TARGET_LAYER_6

#endif // _PRECISION_TEST_FPDATA_H_
